### ISSUE TITLE
Could svgbob be used as a proc macro?

### ISSUE THREAD

**Issue by gilescope** [ivanceras/svgbob#26]
Could svgbob be used as a proc macro?

I'm thinking:
///
///
#[svgbob(
     |
     |--------> Some cool diagram here which would magically turn into svg tags #[doc('<svg>...</svg>')]
     |
)]
fn my_fun() {}

Has someone had a go yet? Would be cool. (Getting svgbob integrated into the main rust docs would be even cooler)

**Comment by ivanceras** [comment]
@gilescope It's definitely cool idea.
And it could also be just as straightforward as:

```
/// Doc comments here
///   and
///  ```svgbob
///  .--------------------.
///  | Diagrams here      |
///  `--------------------'
/// ```
/// together with 
///
/// ```rust
///   fn code_example() {
///        println!("here...");
///  }
/// ```
```
Unfortunately, the @rustdoc team is not as enthusiastic as we are with this hippie cool looking diagramming project.
So I'm just contend with creating a fork of [mdbook](https://github.com/rust-lang-nursery/mdBook) and swapped out the [markdown renderer to use svgbob](https://ivanceras.github.io/spongedown/).

If you could convince the rustdoc team to integrated it with the rust docs, then I would gladly work on it.

**Comment by ivanceras** [comment]
My [mdbook fork](https://github.com/ivanceras/mdbook) is now up-to-date with the latest upstream mdbook and still supports svgbob diagrams. However, I don't see svgbob will be used in rustdocs. I'm closing this issue.

**Comment by yvt** [comment]
FYI: https://github.com/yvt/svgbobdoc

There are many restrictions due to it being a proc-macro such as that it can't be applied on a crate root in a stable Rust, it slows down the compilation, and the interaction with https://github.com/rust-lang/rust/issues/44732 is not great. I wish rustdoc simply integrated svgbob into itself or had provided a plugin interface to allow flexible preprocessing ~~using `dev-dependencies`~~ in a per-crate basis.

**Comment by ivanceras** [comment]
@yvt that's so cool.
