### ISSUE TITLE
Space  between characters disappear

### ISSUE THREAD

**Issue by hanklank** [ivanceras/svgbob#29]
When I generate diagrams containing text it often happens that the spaces between text disappears. The given example will contain OPENFILE and ACCESSFILE in the result. As a dirty fix to this I can add a double space i.e OPEN  FILE and ACCESS  FILE, but that makes the ascii look a bit wacky. 

This will also happen in the demo editor so please try.

Example
```
 |  OPEN FILE              
 |    (1 time)             
 |  ACCESS FILE            
 | 
 \  PRINT DETAILS
```

**Comment by ivanceras** [comment]
This is a visual bug due to the use of multiple fat characters such as O,P,A,C,S. If you inspect element the word are separated apart. It just so happen that the width of word `OPEN` spans a little longer that it almost connects to the next word.

However, you can force them to be treated as one text using escape quote `"`.
```
 |  "OPEN FILE"              
 |    (1 time)             
 |  "ACCESS FILE"            
 | 
 \  PRINT DETAILS
```
