### ISSUE TITLE
Avoid converting words to symbols

### ISSUE THREAD

**Issue by nkh** [ivanceras/svgbob#66]
In some cases svgbob will take a letter inside a word and transform it to a symbol instead for letting it be a character that's part of the word; the examples I have seen where mainly with V, inside a word, be transformed in a down arrow.

svg bob could do a first pass and mark, with the help of a dictionary, the character that are not to be transformed, it should also be possible to input wors or whole dictionary of word to use if one has a technical name not part of the dictionary or uses a foreign language.

**Comment by kimble** [comment]
I have seen a similar case with intervals. 

The dash in the string "10-15" will be converted to a long line.

**Comment by nkh** [comment]
> I have seen a similar case with intervals.
> 
> The dash in the string "10-15" will be converted to a long line.

that may be a hard one to fix but adding 10-15 in a custom dictionary would fix that

**Comment by ivanceras** [comment]
The last [commit](https://github.com/ivanceras/svgbob/commit/a2c13a56e1fbd2a458c90bbb97bb858adc20a5ce) has fix the escaping of characters that are not meant to be interpreted as drawing elements. This feature has already been added on previous version of svgbob (0.4 and below), but due to the major overhaul in the core architecture, this took awhile to be reinstated. 

This will be present in the next release.

**Comment by nkh** [comment]
how is the escaping done?

**Comment by ivanceras** [comment]
Using double quotes, like this:
```
".----------------."
"| Don't draw me  |"
"`----------------'"
```

but this is only available on the next release.

**Comment by nkh** [comment]
how is that a good solution?  it changes the ascii drawing and makes it, I believe very difficult to draw lines.

Wouldn't the dictionary approach be much better? it has the advantage of not modifying the ascii

**Comment by ivanceras** [comment]
I believe it's better and simpler solution, since there is no easy way to determine that words are meant to be interpreted as drawing element or not. Double quotes as explicit escape makes it clear for the algorithm to do this. I don't think the dictionary approach you mentioned here is better, as you could be listing all the words in all the possible languages of the world.

**Comment by andre-dietrich** [comment]
Maybe double `""` could be also used as an escape option, single quotes will still work?

```
"".----------------.""
""| Don't draw me  |""
""`----------------""
```

**Comment by ivanceras** [comment]
@andre-dietrich no, only double quote is used for escaping. The single quotes is used as drawing element such as creating a rounded corner at the bottom of the rectangle.
```bob
.-------.
|       |
'-------'
```
